version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
    - "8080:8080"